Merged CHECKSEQUENCEVERIFY #26
phoreproject/Phore pull request #34
Opened 2018-04-26 06:04 UTC by wqking

2018-04-26 17:15 UTC, meyer9 requested changes
Almost good. Will merge after this small change.

2018-04-26 17:15 UTC, meyer9 commented on src/main.cpp
> -        if (txout.IsEmpty() && !tx.IsCoinBase() && !tx.IsCoinStake())
Please just remove this part instead of commenting it out.

2018-04-27 01:10 UTC, wqking commented
Fixed

2018-04-27 03:58 UTC, meyer9 approved these changes

2018-04-27 03:58 UTC, merged